services:
  - type: web
    name: reviewme-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 5173
    healthCheckPath: /
    autoDeploy: true
